// <auto-generated />
using System;
using HoangVanQuocNhat_BTTrenLop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoangVanQuocNhat_BTTrenLop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413074418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HoangVanQuocNhat_BTTrenLop.Models.DangKyKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayDK")
                        .HasColumnType("datetime2");

                    b.Property<string>("maKh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maSv")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("maKh");

                    b.HasIndex("maSv");

                    b.ToTable("DangKyKhoaHocs");
                });

            modelBuilder.Entity("HoangVanQuocNhat_BTTrenLop.Models.KhoaHoc", b =>
                {
                    b.Property<string>("maKh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maKh");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("HoangVanQuocNhat_BTTrenLop.Models.SinhVien", b =>
                {
                    b.Property<string>("maSv")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maSv");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("HoangVanQuocNhat_BTTrenLop.Models.DangKyKhoaHoc", b =>
                {
                    b.HasOne("HoangVanQuocNhat_BTTrenLop.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("maKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoangVanQuocNhat_BTTrenLop.Models.SinhVien", "SinhVien")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("maSv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("HoangVanQuocNhat_BTTrenLop.Models.KhoaHoc", b =>
                {
                    b.Navigation("DangKyKhoaHocs");
                });

            modelBuilder.Entity("HoangVanQuocNhat_BTTrenLop.Models.SinhVien", b =>
                {
                    b.Navigation("DangKyKhoaHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
