// <auto-generated />
using System;
using HoangVanQuocNhat_BTTrenLop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoangVanQuocNhat_BTTrenLop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413100807_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HoangVanQuocNhat_BTTrenLop.Models.DangKyKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayDK")
                        .HasColumnType("datetime2");

                    b.Property<string>("mkh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("msv")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("mkh");

                    b.HasIndex("msv");

                    b.ToTable("DangKyKhoaHocs");
                });

            modelBuilder.Entity("HoangVanQuocNhat_BTTrenLop.Models.KhoaHoc", b =>
                {
                    b.Property<string>("mkh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenKH")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mkh");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("HoangVanQuocNhat_BTTrenLop.Models.SinhVien", b =>
                {
                    b.Property<string>("msv")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("msv");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("HoangVanQuocNhat_BTTrenLop.Models.DangKyKhoaHoc", b =>
                {
                    b.HasOne("HoangVanQuocNhat_BTTrenLop.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("mkh");

                    b.HasOne("HoangVanQuocNhat_BTTrenLop.Models.SinhVien", "SinhVien")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("msv");

                    b.Navigation("KhoaHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("HoangVanQuocNhat_BTTrenLop.Models.KhoaHoc", b =>
                {
                    b.Navigation("DangKyKhoaHocs");
                });

            modelBuilder.Entity("HoangVanQuocNhat_BTTrenLop.Models.SinhVien", b =>
                {
                    b.Navigation("DangKyKhoaHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
